### PR TITLE
fix: App.tsx types and indentation

### LINKED ISSUE #195: Brand new project fails to compile due to incorrect types
## Steps to reproduce

```
$ npx react-native init MyApp --template react-native-template-typescript
...
$ cd MyApp/
$ npx tsc --skipLibCheck
App.tsx:12:15 - error TS2305: Module '"./node_modules/@types/react"' has no exported member 'Node'.

12  import type {Node} from 'react';
                 ~~~~

App.tsx:31:20 - error TS7031: Binding element 'children' implicitly has an 'any' type.

31  const Section = ({children, title}): Node => {
                      ~~~~~~~~

App.tsx:31:30 - error TS7031: Binding element 'title' implicitly has an 'any' type.

31  const Section = ({children, title}): Node => {
                                ~~~~~


Found 3 errors.
```

## Expected results

A newly created project should be valid Typescript (according to the accompanying `tsconfig.json`).  It would also be nice to be styled e.g. according to some prettier rules.

## Observed results

Running the app works (`npm run ios`) but compiling the code fails and VScode shows the following errors:

- React does not have a type `Node`
- `Section` component uses implicit `any` types (disallowed by strict mode configured in `tsconfig.json`)

These are both introduced in #193.

Also App.tsx shows up bright red/yellow in VScode with prettier for example because *every code line*  is indented by one space.

It would be great if the code validity could be (automatically) tested prior to releases.

### PR DESCRIPTION
**Pull request by radko93**
closes #195

### CODE REVIEW

File: template/App.tsx [hunk 1]
```diff
@@ -28,7 +27,13 @@
...
  } from 'react-native/Libraries/NewAppScreen';
 
- const Section = ({children, title}): Node => {
+ const Section = ({
+   children,
+   title,
+ }: {
+   children: React.ReactNode;
+   title: string;
+ }) => {
```
Comment (emin93) [inline template/App.tsx:36]: `FC<{ title: string }>`?

**Review by emin93 — CHANGES_REQUESTED** [review]

File: template/App.tsx [hunk 2]
```diff
@@ -28,7 +27,13 @@
    ReloadInstructions,
  } from 'react-native/Libraries/NewAppScreen';
 
- const Section = ({children, title}): Node => {
+ const Section = ({
+   children,
```
[the remark this answers is not in the document]
Comment (emin93) [reply template/App.tsx:31]: (i suppose it's because of prettier, in which case it's fine and you can resolve this conversation.)

**Review by emin93 — APPROVED** [review]
